import json
import os
import subprocess
import urllib.request
import hashlib

META_URL = "https://kamori.goats.dev/Dalamud/Release/Meta"
BRANCH_FILE = "dalamud-branches.json"


def runtime_ver_to_nix_sdk(runtime_version):
    parts = runtime_version.split(".")
    major, minor = parts[0], parts[1]
    return f"sdk_{major}_{minor}"


def generate_branch(branch, info):
    downloadUrl = info["downloadUrl"]
    version = info["assemblyVersion"]
    runtimeVersion = info["runtimeVersion"]

    print(
        f"Generating branch info for {branch} (v{version}) with runtime {runtimeVersion}"
    )
    result = subprocess.check_output(
        [
            "nix",
            "store",
            "prefetch-file",
            "--unpack",
            "--hash-type",
            "sha256",
            "--json",
            downloadUrl,
        ],
        stderr=subprocess.DEVNULL,
        text=True,
    )
    return branch, {
        "version": version,
        "runtimeVersion": runtimeVersion,
        "downloadUrl": downloadUrl,
        "nix": {
            "hash": json.loads(result)["hash"],
            "dotnetSdkVersion": runtime_ver_to_nix_sdk(runtimeVersion),
        },
    }


# Fetch remote branch metadata.
print(f"Fetching release information from {META_URL}")
with urllib.request.urlopen(META_URL) as response:
    meta = json.load(response)
    checksum = hashlib.sha256(
        json.dumps(meta, indent=None, sort_keys=True, ensure_ascii=True).encode("utf-8")
    ).hexdigest()

# Check if anything changed since last run.
if os.path.exists(BRANCH_FILE):
    try:
        with open(BRANCH_FILE, "r") as f:
            existing_checksum = json.load(f).get("_generated", {}).get("checksum")
            if existing_checksum == checksum:
                print("No changes found since last update")
                exit(0)
    except (json.JSONDecodeError, KeyError):
        pass

# Update local branch data.
branches = dict(generate_branch(branch, info) for branch, info in meta.items())
with open(BRANCH_FILE, "w") as f:
    json.dump(
        {
            "_generated": {
                "note": "This file is autogenerated, do not edit manually.",
                "source": META_URL,
                "checksum": checksum,
            },
            "branches": branches,
        },
        f,
        indent=2,
    )
print(f"Updated {BRANCH_FILE} ({checksum})")
